version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: army_ecommerce_backend
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - DATABASE_URL=file:/app/prisma/dev.db
      - JWT_SECRET=army_ecommerce_secret_key_2026_Quang_Trung_Soldier
      - JWT_EXPIRES_IN=7d
      - BASE_URL=http://localhost:3000 # Cần thay bằng http://<GCP-VM-IP>:3000 khi deploy
    volumes:
      - ./uploads:/app/uploads
      - ./prisma/dev.db:/app/prisma/dev.db
    restart: always
